<?php

namespace Tests\Feature\Console;

use App\AI\Contracts\AiProviderInterface;
use App\AI\Data\AiGenerationResult;
use App\Enums\ContentStatus;
use App\Enums\ContentType;
use App\Enums\SummaryStatus;
use App\Models\Content;
use Database\Seeders\PromptSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ContentCommandsTest extends TestCase
{
    use RefreshDatabase;

    public function test_generate_summary_command_reports_not_found_cleanly(): void
    {
        $this->artisan('content:generate-summary 1')
            ->expectsOutput('Content not found for [1].')
            ->expectsOutput('No content records exist yet.')
            ->assertExitCode(1);
    }

    public function test_create_sample_command_creates_content(): void
    {
        $this->artisan('content:create-sample --slug=from-command --title="From Command" --type=post --status=draft')
            ->expectsOutput('Sample content created.')
            ->assertExitCode(0);

        $this->assertDatabaseHas('contents', [
            'slug' => 'from-command',
            'title' => 'From Command',
            'type' => ContentType::POST->value,
            'status' => ContentStatus::DRAFT->value,
        ]);
    }

    public function test_generate_summary_command_works_with_slug_argument(): void
    {
        $this->seed(PromptSeeder::class);

        app()->bind(AiProviderInterface::class, function () {
            return new class implements AiProviderInterface
            {
                public function generate(string $prompt, array $options = []): AiGenerationResult
                {
                    return new AiGenerationResult(
                        text: json_encode([
                            'summary_tldr' => 'Generated by command',
                            'summary_bullets' => ['A', 'B'],
                            'summary_meta_description' => 'Meta',
                            'summary_faq' => [['question' => 'Q1', 'answer' => 'A1']],
                            'summary_tags' => ['tag1'],
                        ]) ?: '{}',
                        model: 'fake-model',
                        tokensIn: 33,
                        tokensOut: 11,
                    );
                }
            };
        });

        $content = Content::create([
            'type' => ContentType::POST,
            'slug' => 'command-summary',
            'title' => 'Command Summary',
            'body' => 'Markdown body',
            'locale' => 'en',
            'status' => ContentStatus::DRAFT,
        ]);

        $this->artisan('content:generate-summary command-summary')
            ->expectsOutput('Summary generated.')
            ->expectsOutput("Content ID: {$content->id}")
            ->assertExitCode(0);

        $summary = $content->summary()->first();

        $this->assertNotNull($summary);
        $this->assertSame(SummaryStatus::READY, $summary?->status);
        $this->assertSame('Generated by command', $summary?->summary_tldr);
    }
}

