apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "novacms.fullname" . }}-ollama-models
  labels:
    {{- include "novacms.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
  {{- if .Values.ollama.persistence.storageClass }}
  storageClassName: {{ .Values.ollama.persistence.storageClass }}
  {{- end }}
