<x-filament-panels::page>
    <div class="space-y-6">
        <x-filament.ui.hero
            tone="slate"
            :eyebrow="strtoupper((string) $record->type->value) . ' Record'"
            :title="$record->title"
            :description="'Slug ' . $record->slug . ' · locale ' . $record->locale . ' · updated ' . $record->updated_at?->diffForHumans()"
        >
            <x-slot:aside>
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-300">Operator Notes</p>
                <div class="mt-4 space-y-3 text-sm text-slate-200">
                    <div class="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
                        <p class="font-semibold text-white">Next step</p>
                        <p class="mt-1 text-slate-300">{{ $nextStep }}</p>
                    </div>
                    <div class="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
                        <p class="font-semibold text-white">Latest event</p>
                        <p class="mt-1 text-slate-300">{{ $latestEventName }} · {{ $latestEventWhen }}</p>
                    </div>
                    <div class="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
                        <p class="font-semibold text-white">Publish gate</p>
                        <p class="mt-1 text-slate-300">{{ $qualityGatePassed ? 'Structured output is ready for editorial review.' : 'A required summary block is still missing or stale.' }}</p>
                    </div>
                </div>
            </x-slot:aside>

            <div class="mt-5 flex flex-wrap gap-2">
                <span @class([
                    'inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ring-1',
                    'bg-emerald-400/15 text-emerald-100 ring-emerald-300/20' => $publicationStatus === 'published',
                    'bg-amber-400/15 text-amber-100 ring-amber-300/20' => $publicationStatus === 'draft',
                    'bg-slate-400/15 text-slate-100 ring-slate-300/20' => $publicationStatus === 'archived',
                ])>
                    {{ ucfirst($publicationStatus) }}
                </span>
                <span @class([
                    'inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ring-1',
                    'bg-emerald-400/15 text-emerald-100 ring-emerald-300/20' => $summaryStatus === 'ready',
                    'bg-sky-400/15 text-sky-100 ring-sky-300/20' => $summaryStatus === 'generating',
                    'bg-amber-400/15 text-amber-100 ring-amber-300/20' => $summaryStatus === 'pending',
                    'bg-rose-400/15 text-rose-100 ring-rose-300/20' => $summaryStatus === 'failed',
                ])>
                    AI {{ ucfirst($summaryStatus) }}
                </span>
                <span class="inline-flex items-center rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-slate-200 ring-1 ring-white/10">
                    Locale {{ strtoupper((string) $record->locale) }}
                </span>
                <span class="inline-flex items-center rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-slate-200 ring-1 ring-white/10">
                    Hash {{ substr((string) $record->content_hash, 0, 12) }}
                </span>
            </div>
        </x-filament.ui.hero>

        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <x-filament.ui.metric-card
                label="Words"
                :value="number_format($wordCount)"
                description="Source body size for this record."
                tone="indigo"
            />
            <x-filament.ui.metric-card
                label="Bullets"
                :value="$bulletCount"
                description="Structured bullet points generated by the active prompt."
                tone="sky"
            />
            <x-filament.ui.metric-card
                label="FAQ Pairs"
                :value="$faqCount"
                description="Question and answer pairs extracted from the source."
                tone="amber"
            />
            <x-filament.ui.metric-card
                label="Tags"
                :value="$tagCount"
                description="Generated tags available for downstream consumers."
                tone="emerald"
            />
        </section>

        <section class="grid gap-6 xl:grid-cols-[1.7fr_0.8fr]">
            <div class="space-y-6">
                {{ $this->infolist }}
            </div>

            <div class="space-y-6 xl:sticky xl:top-6 xl:self-start">
                <x-filament.ui.panel
                    eyebrow="Quality Gate"
                    title="Publishing Readiness"
                    :badge="$qualityGatePassed ? 'ready to review' : 'needs attention'"
                    :tone="$qualityGatePassed ? 'emerald' : 'amber'"
                >
                    <div class="space-y-3 text-sm text-gray-700 dark:text-gray-200">
                        <div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-700">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">TL;DR present</p>
                            <p class="mt-1">{{ filled($record->summary?->summary_tldr) ? 'Yes' : 'Missing' }}</p>
                        </div>
                        <div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-700">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">Bullets and tags</p>
                            <p class="mt-1">{{ $bulletCount > 0 && $tagCount > 0 ? 'Complete' : 'Incomplete' }}</p>
                        </div>
                        <div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-700">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">FAQ coverage</p>
                            <p class="mt-1">{{ $faqCount > 0 ? 'At least one pair generated' : 'No FAQ pairs yet' }}</p>
                        </div>
                    </div>
                </x-filament.ui.panel>

                <x-filament.ui.panel
                    eyebrow="Generation Trace"
                    title="Latest Run Context"
                >
                    <div class="space-y-3 text-sm text-gray-700 dark:text-gray-200">
                        <div class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">Event</p>
                            <p class="mt-1">{{ $latestEventName }} · {{ $latestEventWhen }}</p>
                        </div>
                        <div class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">Model and prompt</p>
                            <p class="mt-1">{{ $record->summary?->model ?? 'n/a' }} · prompt {{ $record->summary?->prompt_version ?? 'n/a' }}</p>
                        </div>
                        <div class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">Latency and tokens</p>
                            <p class="mt-1">{{ is_numeric($record->summary?->generation_ms) ? ((int) $record->summary?->generation_ms) . ' ms' : 'n/a' }} · in {{ $record->summary?->tokens_in ?? 'n/a' }} / out {{ $record->summary?->tokens_out ?? 'n/a' }}</p>
                        </div>
                        <div class="rounded-2xl border border-gray-200 px-4 py-3 dark:border-gray-700">
                            <p class="font-semibold text-gray-900 dark:text-gray-100">Latest message</p>
                            <p class="mt-1 leading-6">{{ $latestEventMessage }}</p>
                        </div>
                    </div>
                </x-filament.ui.panel>

                <x-filament.ui.panel
                    eyebrow="Working Notes"
                    title="Recommended Flow"
                >
                    <ol class="space-y-3 text-sm text-gray-700 dark:text-gray-200">
                        <li class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <span class="font-semibold text-gray-900 dark:text-gray-100">1. Review the summary blocks</span>
                            <p class="mt-1">Check TL;DR signal, bullet quality, tags, and FAQ usefulness before touching status.</p>
                        </li>
                        <li class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <span class="font-semibold text-gray-900 dark:text-gray-100">2. Change status only after validation</span>
                            <p class="mt-1">The quick status action is safe, but publishing should follow the quality gate.</p>
                        </li>
                        <li class="rounded-2xl bg-gray-50 px-4 py-3 dark:bg-gray-800">
                            <span class="font-semibold text-gray-900 dark:text-gray-100">3. Use Queue Center for stalled runs</span>
                            <p class="mt-1">If the record stays pending or generating for too long, move to Queue Center or System Health.</p>
                        </li>
                    </ol>
                </x-filament.ui.panel>
            </div>
        </section>
    </div>
</x-filament-panels::page>
